########################################
## DB-Demo-2 (c) 2024/02/07 Jan Klimo ##
########################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-2
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80