########################################
## DB-Demo-2 (c) 2024/02/07 Jan Klimo ##
########################################

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
commonLabels:
  app: nginx-demo2-db
resources:
- deployment.yaml
- service.yaml
- job.yaml